version: '3.7'
services:
  ros-px4-foxy:
    image: realsense:latest
    container_name: realsense
    build:
      context: .
      dockerfile: Dockerfile
    devices:
      - /dev/bus/usb:/dev/bus/usb
      - /dev/video0:/dev/video0 
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
    environment:
      - DISPLAY=${DISPLAY}
      - LIBGL_ALWAYS_SOFTWARE=1
    network_mode: "host"
    stdin_open: true
    tty: true
    privileged: true

